version: '3.8' # ระบุเวอร์ชันของ docker-compose

services:
  mysql:
    image: mysql:8.0 # ใช้ MySQL เวอร์ชัน 8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: hotbun101 # รหัสผ่านสำหรับ root
      MYSQL_DATABASE: hotbunDB # ชื่อฐานข้อมูลเริ่มต้น
      MYSQL_USER: adminhotbun # ชื่อผู้ใช้ที่สามารถเข้าถึงฐานข้อมูล
      MYSQL_PASSWORD: hotbun2024 # รหัสผ่านสำหรับผู้ใช้
    ports:
      - '3306:3306' # เปิดพอร์ต 3306 สำหรับ MySQL
    volumes:
      - mysql_data:/var/lib/mysql # ใช้ volume สำหรับเก็บข้อมูล

  phpmyadmin:
    image: phpmyadmin/phpmyadmin # ใช้ phpMyAdmin ภาพ
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql # ชื่อของบริการ MySQL
      PMA_PORT: 3306 # พอร์ตที่ MySQL ใช้
    ports:
      - '8080:80' # เปิดพอร์ต 8080 สำหรับ phpMyAdmin
    depends_on:
      - mysql # ต้องรอให้ MySQL ทำงานก่อน

volumes:
  mysql_data:
